apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lacework-config
spec:
  provider: azure
  parameters:
    keyvaultName: "YOUR_KEY_VAULT"
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    objects:  |
      array:
        - |
          objectName: laceworkK8sConfig
          objectAlias: config.json
          objectType: secret
          filePermission: "0640"
    tenantId: "YOUR_TENANT_ID"
