apiVersion: apps/v1

kind: DaemonSet
metadata:
  name: lacework-agent
  labels:
    tier: monitoring
    app: lacework-agent
spec:
  selector:
    matchLabels:
      name: lacework
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: lacework
    spec:
      tolerations: 
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      terminationGracePeriodSeconds: 20
      hostPID: true
      hostNetwork: true
      containers:
      - name: lacework
        image: lacework/datacollector
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1450Mi"
        securityContext:
          privileged: true
        env:
          - name: LaceworkLogStdout
            value: "true"
        volumeMounts:
          - name: config
            mountPath: /var/lib/lacework/config
          - name: dev
            mountPath: /dev
          - name: run-sock
            mountPath: /var/run/docker.sock
          - name: run-pid
            mountPath: /var/run/docker.pid
          - name: sys
            mountPath: /sys
          - name: log
            mountPath: /var/log
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: group
            mountPath: /etc/group
            readOnly: true
          - name: hostlacework
            mountPath: /var/lib/lacework/collector
          - name: hostlaceworkcontroller
            mountPath: /var/lib/lacework/controller
          - name: hostroot
            mountPath: /laceworkfim
            readOnly: true
          - name: podinfo
            mountPath: /etc/podinfo
      volumes:
        - name: dev
          hostPath:
              path: /dev
        - name: run-sock
          hostPath:
              path: /var/run/docker.sock
        - name: run-pid
          hostPath:
              path: /var/run/docker.pid
        - name: sys
          hostPath:
              path: /sys
        - name: log
          hostPath:
              path: /var/log
        - name: passwd
          hostPath:
              path: /etc/passwd
        - name: group
          hostPath:
              path: /etc/group
        - name: hostroot
          hostPath:
              path: /
        - name: hostlacework
          hostPath:
              path: /var/lib/lacework/collector
        - name: hostlaceworkcontroller
          hostPath:
              path: /var/lib/lacework/controller
        - name: config
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "lacework-config"
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
