# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  displayName: 'Run a one-line script'
  inputs:
    script: |
      docker run \
      -e SCAN_COMMAND=tf-scan \
      -e LW_ACCOUNT=lwintmarkfink \
      -e LW_API_KEY=LWINTMAR_415AEA3ADA56D227E1FE86EC3A510964FFF3CC78F7267F8 \
      -e LW_API_SECRET=_002ecca16c64d2f86bc73ae07e47a776 \
      -v $(Build.SourcesDirectory):/app/src \
      -e WORKSPACE=src \
      docker.io/lacework/codesec-iac:latest
