# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  displayName: 'Lacework IAC scan'
  inputs:
    script: |
      docker run \
      -e SCAN_COMMAND=tf-scan \
      -e LW_ACCOUNT=$(LW_ACCOUNT) \
      -e LW_API_KEY=$(LW_API_KEY) \
      -e LW_API_SECRET=$(LW_API_SECRET) \
      -v $(Build.SourcesDirectory):/app/src \
      -e WORKSPACE=src \
      -e EXIT_FLAG='high' \
      docker.io/lacework/codesec-iac:latest
